services:
  spring_batch-mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - batch_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      spring_batch-network:
        aliases:
          - spring_batchbase
    hostname: "spring_batchbase"
    container_name: spring_batch-mysql
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

networks:
  spring_batch-network:
    name: "spring_batch-network"

volumes:
  batch_data:
    name: "batch_data"
